config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'

  # get '/users', to: 'users#index'

  # get '/users/:id', to: 'users#show'

  # get '/users/:id/posts', to: 'posts#index'

  # get '/users/:id/posts/new', to: 'posts#new'

  # get '/users/:id/posts/:post_id', to: 'posts#show'

  # get 'users/:id/posts/:post_id/comments/new', to: 'comments#new'

  # post 'users/:id/posts/:post_id/comments/create', to: 'comments#create'

  # post 'users/:id/posts/:post_id/likes/create', to: 'likes#create'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :create, :destroy] do
      resources :comments, only: [:new, :index, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  post '/users/:id/posts/create', to: 'posts#create'

  namespace :api do
    namespace :v1 do
      get '/user/:id/posts', to: 'posts#index'
      get '/post/:id/comments', to: 'comments#index'
      post 'post/:id/comment', to: 'comments#create'
    end
  end

  post '/auth/login', to: 'authentication#login'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  before_save -> { User.find_by(id: author.id).increment!(:posts_counter) }
  before_destroy -> { User.find_by(id: author.id).decrement!(:posts_counter) }

  scope :get_5_comments, ->(post) { post.comments.order('created_at DESC').limit(5) }

  validates :title, presence: true
  validates :author, presence: true
  validates :title, length: { in: 1..250 }
  validates :likes_counter, :comment_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @posts = Post.where(author_id: params[:id])
    render json: @posts, except: %i[created_at updated_at]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @posts = Post.where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    if current_user
      @post = Post.new(post_params)
      @post.author_id = current_user.id
      @post.likes_counter = 0
      @post.comment_counter = 0

      if @post.save
        redirect_to users_path
      else
        render :new
      end
    else
      redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])

    @post.likes.destroy_all
    @post.comments.destroy_all

    @post.destroy

    respond_to do |format|
      format.html { redirect_to "/users/#{params[:user_id]}/posts", notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<%= render 'shared/user_profile', user: @user %>

<% @posts.each  do  |post|%>
<div class="boxed comments_container">
    <a href="/users/<%= post.author_id%>/posts/<%= post.id %>"><%= post.title%></a>
        <p>
           <%= post.text%>
        </p>
        <p class="comments_likes">
            Comments: <%= post.comment_counter %> Likes: <%= post.likes_counter%>
        </p>
</div>
<div class="boxed">
<% Post.get_5_comments(post).includes([:author]).each  do |comment|%>
    <p><%= comment.author.name%> - <%= comment.text %></p>
    <%end%>
</div>
<br />
<%end%>
<div class="buttton_container">
<button class="all_post_btn">Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
<% end%>
<%= form_with url: "/users/21/posts/create", model: @post do |form|%>
<%= form.label :title %>
<%= form.text_field :title%>
<br/>
<%= form.label :text %>
<%= form.text_field :text%>
<br/>
<%= form.submit%>

<%end%>

app/views/posts/show.html.erb
<div class="posts_show_container">
<div class="boxed">
<div class="posts_info">
<p><%= @post.title%> by <%= @post.author.name%></P>
<p>Comments: <%= @post.comment_counter%> likes: <%= @post.likes_counter %></p>
</div>

<p>
<%= @post.text%>
</p>
</div>
<br />
<%= render 'shared/like' %>
<a href=<%="/users/#{params[:user_id]}/posts/#{@post.id}/comments/new"%>>Comment</a>
<% if can? :destroy, @post %>
 <%= form_with(model: @post, url: user_post_path(params[:user_id], @post), method: :delete, data: { confirm: "Are you sure?" }) do |form| %>
  <%= form.submit "Destroy Post" %>
<% end %>
<% end %>

<%# <%= link_to "Destroy Post", "/users/#{params[:user_id]}/posts/#{@post.id}", method: :delete, data: { confirm: "Are you sure?" } %> 
<%# user_post_path(params[:user_id], @post) %>
<div class="boxed">
    <% @post.comments.includes([:author]).each do |comment| %>
     <p><%= comment.author.name%>: <%= comment.text %></p>

     <% if can? :destroy, @post %>
      <%= form_with(model: @comment, url: user_post_comment_path(params[:user_id], @post), method: :delete, data: { confirm: "Are you sure?" }) do |form| %>
        <%= form.hidden_field :comment_info, value: "#{comment.id}" %>
        <%= form.submit "Destroy Comment" %>
      <% end %>
     <% end %>
    <%end%>

</div>

</div>